[workspace]
members = [
	"mmio",
	"pci",
	"tts",
	"rtc",
	"serial_terminal",
	"screen",
	"gpu",
	"heap",
	"hid",
	"plic",
	"apm",
	"bsod",
	"sgl",
	"health_analyzer",
	"stack_string",
	"clint",
	"net_hub",
	"hdd",
	"flash",
	"floppy_drive",
]
resolver = "2"
